### ISSUE TITLE
[BUG]  Unable to remove citrixadc_policystringmap_pattern_binding with / or special char

### ISSUE THREAD

**Issue by RafaelloLollipop** [citrix/terraform-provider-citrixadc#1018] opened 2023-03-14 14:11 UTC
# Bug Report

**Describe the bug**

If key in string map contains "/'" or "%" it can not be removed by terraform.
But i'm pretty sure that it was working like 1-2 months ago.

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl

resource "citrixadc_policystringmap" "tf_policystringmap" {
  name    = "tf_tests"
}


resource "citrixadc_policystringmap_pattern_binding" "tf_bind1" {
  name  = "tf_tests"
  key   = "test"
  value = "test"
}


resource "citrixadc_policystringmap_pattern_binding" "tf_bind2" {
  name  = "tf_tests"
  key   = "test/test"
  value = "random"
}

```

Plan:

```
-------------------------------------------------------------------------
string_maps: Perform terraform plan
-------------------------------------------------------------------------

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.ns_tst_string_maps.citrixadc_policystringmap.tf_policystringmap will be created
  + resource "citrixadc_policystringmap" "tf_policystringmap" {
      + comment = (known after apply)
      + id      = (known after apply)
      + name    = "tf_tests"
    }

  # module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind1 will be created
  + resource "citrixadc_policystringmap_pattern_binding" "tf_bind1" {
      + id    = (known after apply)
      + key   = "test"
      + name  = "tf_tests"
      + value = "test"
    }

  # module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind2 will be created
  + resource "citrixadc_policystringmap_pattern_binding" "tf_bind2" {
      + id    = (known after apply)
      + key   = "test/test"
      + name  = "tf_tests"
      + value = "random"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

After apply:

![image](https://user-images.githubusercontent.com/6643759/225026765-14371a13-0b8c-4ecc-93c4-a5a8ceb27bb4.png)

Removing bindings:

```hcl

resource "citrixadc_policystringmap" "tf_policystringmap" {
  name    = "tf_tests"
}

```

plan:
```
string_maps: Perform terraform plan
-------------------------------------------------------------------------
module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind1: Refreshing state... [id=tf_tests,test]
module.ns_tst_string_maps.citrixadc_policystringmap.tf_policystringmap: Refreshing state... [id=tf_tests]
module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind2: Refreshing state... [id=tf_tests,test/test]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind1 will be destroyed
  # (because citrixadc_policystringmap_pattern_binding.tf_bind1 is not in configuration)
  - resource "citrixadc_policystringmap_pattern_binding" "tf_bind1" {
      - id    = "tf_tests,test" -> null
      - key   = "test" -> null
      - name  = "tf_tests" -> null
      - value = "test" -> null
    }

  # module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind2 will be destroyed
  # (because citrixadc_policystringmap_pattern_binding.tf_bind2 is not in configuration)
  - resource "citrixadc_policystringmap_pattern_binding" "tf_bind2" {
      - id    = "tf_tests,test/test" -> null
      - key   = "test/test" -> null
      - name  = "tf_tests" -> null
      - value = "random" -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.


```
apply:

```
-------------------------------------------------------------------------
string_maps: Perform terraform apply
-------------------------------------------------------------------------
module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind2: Destroying... [id=tf_tests,test/test]
module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind1: Destroying... [id=tf_tests,test]
module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind2: Destruction complete after 0s
module.ns_tst_string_maps.citrixadc_policystringmap_pattern_binding.tf_bind1: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 2 destroyed.

```

State:

![image](https://user-images.githubusercontent.com/6643759/225027150-f0fb63b1-8c38-4932-88d7-0327966beadf.png)

**Expected behaviour**
Both citrixadc_policystringmap_pattern_binding. removed

**Environment (please complete the following information):**
 - ubuntu
```
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/citrix/citrixadc v1.32.0    ( I checked also on v1.8.0)
+ provider registry.terraform.io/hashicorp/aws v3.76.1
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0

```
```
go version go1.18 linux/amd64
```

**Additional context**
-

**Comment by ravager-dk** [comment] 2023-04-04 08:22
This issue is caused by the AddResource function in the client escaping special characters, while the DeleteResourceWithArgs does not.

**Comment by rohit-myali** [comment] 2023-04-20 07:50
Hello @RafaelloLollipop ,
Thanks for raising this issue. I did fix this issue and it will be released to the terraform registry in our next releases. I will update you on that soon.

Hey @ravager-dk , thanks for working on this issue, I saw your PR but currently we are not accepting 3rd party contribution due to some company policies. Our internal team is working on accepting 3rd part contribution we will update this soon.

Thanks,
Rohit

**Comment by ravager-dk** [comment] 2023-04-20 08:13
> Hello @RafaelloLollipop ,
> Thanks for raising this issue. I did fix this issue and it will be released to the terraform registry in our next releases. I will update you on that soon.
> 
> Hey @ravager-dk , thanks for working on this issue, I saw your PR but currently we are not accepting 3rd party contribution due to some company policies. Our internal team is working on accepting 3rd part contribution we will update this soon.
> 
> Thanks,
> Rohit

Hi Rohit

No problem, I am actually internal, just not in engineering.

Regards,
Martin Nygaard Jensen

**Comment by rohit-myali** [comment] 2023-05-06 15:56
Hi @RafaelloLollipop ,
Thanks for raising this issue.
I have fixed the resource you can use the latest terraform plugin [v1.34.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/policystringmap_pattern_binding). 

Thanks
Rohit

**Closed by rohit-myali** 2023-05-06 15:56 UTC
